# Generated by Django 5.2.1 on 2025-05-20 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizzatore',
            fields=[
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=30)),
                ('data_nascita', models.DateField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('luogo', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('biglietti_disponibili', models.IntegerField()),
                ('organizzatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_Hub.organizzatore')),
            ],
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valutazione', models.IntegerField()),
                ('commento', models.TextField()),
                ('data_recensione', models.DateField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_Hub.evento')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_Hub.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_biglietti', models.IntegerField()),
                ('data_prenotazione', models.DateField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_Hub.evento')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_Hub.utente')),
            ],
        ),
    ]
