# Generated by Django 5.2.1 on 2025-05-27 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrello',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_biglietti', models.IntegerField()),
                ('data_aggiunta', models.DateField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_Hub.evento')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_Hub.utente')),
            ],
            options={
                'unique_together': {('utente', 'evento')},
            },
        ),
    ]
