# Generated by Django 5.2.1 on 2025-05-29 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Hub', '0003_evento_prezzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='stato',
            field=models.CharField(choices=[('attivo', 'Attivo'), ('usato', 'Usato'), ('cancellato', 'Cancellato'), ('rimborsato', 'Rimborsato')], default='attivo', max_length=20),
        ),
        migrations.AddField(
            model_name='utente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='EventoSalvato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_salvataggio', models.DateField(auto_now_add=True)),
                ('notifiche_attive', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_Hub.evento')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_Hub.utente')),
            ],
            options={
                'unique_together': {('utente', 'evento')},
            },
        ),
    ]
