# Generated by Django 5.2.1 on 2025-05-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Hub', '0004_prenotazione_stato_utente_telefono_eventosalvato'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
